### ISSUE TITLE
Unable to cast object of type 'System.Fabric.SingletonPartitionInformation' to type 'System.Fabric.Int64RangePartitionInformation'

### ISSUE THREAD

**Issue by ledpup** [SoCreate/service-fabric-distributed-cache#21]
I'm testing the SetAsync. The code is:

```
            var options = new DistributedCacheEntryOptions
            {
                SlidingExpiration = TimeSpan.FromSeconds(300)
            };
            await _distributedCache.SetAsync("AccessToken", Encoding.UTF8.GetBytes("55"), options);
```

It's throwing with the following stack trace.

System.InvalidCastException: Unable to cast object of type 'System.Fabric.SingletonPartitionInformation' to type 'System.Fabric.Int64RangePartitionInformation'.
   at SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator.<>c__DisplayClass12_0.<GetPartitionInformationForCacheKeyAsync>b__0(Partition p)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator.GetPartitionInformationForCacheKeyAsync(String cacheKey)
   at SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator.GetCacheStoreProxy(String cacheKey)
   at SoCreate.Extensions.Caching.ServiceFabric.ServiceFabricDistributedCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)

**Comment by ledpup** [comment]
I'm running 2.1.3. Going to drop back a version or two and test that. Then try cloning the repo and have a look.

**Comment by ledpup** [comment]
I cloned and included the project in the solution. After doing that, I could not reproduce the issue. It only happens when including it as a NuGet package 2.1.3 or 2.1.1 so far (the two packages I've tested).

**Comment by ledpup** [comment]
Reading... clearly I don't know enough about Service Fabric.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-partitioning

It doesn't seem possible that my service switched from getting that error to not getting it after only just cloning the library. Somehow it looks like I've switched it from being a SingletonPartition to a Int64RangePartition.

Right now the only thing I can see wrong with this repo is that it could probably have a better error message. I'll keep investigating this.

**Comment by ledpup** [comment]
I figured out how the above occurred. I had my SingletonPartition app working because on my other machine I'd run the DistributedCache app in the example code of the repo. This means my SingletonPartition was using the cache store created by the demo. Once you remove the demo application, the cast exception re-occurs.

I then resolved the issue properly by making my application a UniformInt64Partition in ApplicationManifest.xml, same as in the example code.

Next issue is that I get this exception. Once again, it's a difference between the example application and mine.

```
SoCreate.Extensions.Caching.ServiceFabric.CacheStoreException: An exception occurred while accessing cache store.
 ---> System.Fabric.FabricInvalidAddressException: NamedEndpoint 'CacheStoreServiceListener' not found in the address '{"Endpoints":{"":"http:\/\/mymachine:8686"}}' for partition '6b83ffa3-c4d8-4db0-bf5d-a58de373599b'
   at Microsoft.ServiceFabric.Services.Communication.Client.CommunicationClientCacheEntry`1.GetEndpointAddressForNamedEndpoint()
   at Microsoft.ServiceFabric.Services.Communication.Client.CommunicationClientCacheEntry`1.GetEndpoint()
   at Microsoft.ServiceFabric.Services.Communication.Client.CommunicationClientFactoryBase`1.CreateNewClientAsync(String listenerName, String requestId, ResolvedServicePartition previousRsp, CommunicationClientCacheEntry`1 cacheEntry, CancellationToken cancellationToken)
```

**Comment by ledpup** [comment]
A lot more reading later... I figured out how to use this library though it turns out I don't need a distributed cache. I only needed the most basic of caching. Just rolled it from the basic stateful SF functionality.

Thanks for writing this though. I'll keep it in mind for the future.
